language: python

python:
    - 2.7
    - 3.5

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
            - gfortran

env:
    global:
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - CONDA_DEPENDENCIES='sherpa'
        - CONDA_CHANNELS='sherpa'

    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:

        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'

        # Sherpa 4.8.2 is the first to support python
        - python: 3.5
          env: SHERPA_VERSION>=4.8.2 

        - python: 3.5
          env: SHERPA_VERSION>=4.8.2 ASTROPY_VERSION=dev

        # Testing the docs building
        - python: 3.5
          env: SHERPA_VERSION>=4.8.2 SETUP_CMD='build_sphinx -w'
               CONDA_DEPENDENCIES='sherpa ipython'

        # Test old numpy versions
        - python: 3.5
          env: SHERPA_VERSION>=4.8.2 NUMPY_VERSION=1.10
        - python: 2.7
          env: NUMPY_VERSION=1.9
        - python: 2.7
          env: NUMPY_VERSION=1.8

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then
         coveralls --rcfile='saba/tests/coveragerc';
      fi

notifications:
  email: false
